### PR TITLE
Fix pino-http types

### PR DESCRIPTION
**Pull request by jarcodallo**
This PR will fix the problem with pino and pino-http types.

**NOTE**: I installed pino-http from master branch, because I am waiting for the next release.

[Add support for default and name export with TypeScript](https://github.com/pinojs/pino-http/pull/188)

### CODE REVIEW

**Comment by jarcodallo** [comment]
Hi @iamolegga please take a look of this PR. let me know if you have any question.

**Comment by iamolegga** [comment]
Hello @jarcodallo at first
image

Second, I'm just wondering do we really need to change the code of the current library instead of fixing types in parent libs – since types are moved from separate packages I thought that all those bugs are existing because of broken exports, which could be fixed and work pretty same as before just imported underhood from the same package as the lib, instead of separate types package.

Third, why do we need `pino` in peer deps, as it goes as a [direct dependency](https://github.com/pinojs/pino-http/blob/master/package.json#L10) of `pino-http`?

Forth, of course, now it's unsafe to merge this with github link instead of fixed npm version.

Thanks

**Comment by jarcodallo** [comment]
> Hello @jarcodallo at first image
> 
> Second, I'm just wondering do we really need to change the code of the current library instead of fixing types in parent libs – since types are moved from separate packages I thought that all those bugs are existing because of broken exports, which could be fixed and work pretty same as before just imported underhood from the same package as the lib, instead of separate types package.
> 
> Third, why do we need `pino` in peer deps, as it goes as a [direct dependency](https://github.com/pinojs/pino-http/blob/master/package.json#L10) of `pino-http`?
> 
> Forth, of course, now it's unsafe to merge this with github link instead of fixed npm version.
> 
> Thanks

First: resolved.
Second:  Pino v7.5 removed the export for BaseLogger, because if you want to extends the logger the correct way to do it is using the [Logger type](https://github.com/pinojs/pino/blob/v7.5.1/pino.d.ts#L209) that includes the BaseLogger and `EventEmitter` class implementation.
Third: we need it, because `@nestjs/platform-fastify` uses pino@6.x
image

Forth: Yeah we need to wait for the release version. 🚀 

Thanks for the fast reply.

**Comment by iamolegga** [comment]
1. I'm not sure. I still can see this message. I believe this is due to updates in both commits in `package-lock` file. I suggest just maybe start from the latest `master`?
2. Am I correct that this is a breaking change in a minor release?) Can you please point me to the commit with this changes?
3. Am I correct that this is devDeps tree? So for end-user of this lib there will not be any need for this, or not? I still didn't get it.
4. Ok then, that wasn't clear for me at the start 😀

**Comment by jarcodallo** [comment]
> 1. I'm not sure. I still can see this message. I believe this is due to updates in both commits in `package-lock` file. I suggest just maybe start from the latest `master`?
> 2. Am I correct that this is a breaking change in a minor release?) Can you please point me to the commit with this changes?
> 3. Am I correct that this is devDeps tree? So for end-user of this lib there will not be any need for this, or not? I still didn't get it.
> 4. Ok then, that wasn't clear for me at the start 😀

1.- I did haha. I don't see any warning.
image
2.- I don't think is a breaking change, BUT! using a major release of `pino` in your dependencies can be a reason to bump the major version of `nestjs-pino`. 6 days ago pino team merged a [PR#1195](https://github.com/pinojs/pino/pull/1195) that moved the BaseLogger outside of the namespace. They just merged a [PR#1246](https://github.com/pinojs/pino/pull/1246) that exported it the BaseLogger again, so we need to wait for the release and I will update this PR.
4.- Sorry for the misunderstood :D

**Comment by iamolegga** [comment]
1. I think that's because you've merged upstream master to your branch **after** making changes. May I ask you to either squash all commits and force-push it or create a new branch from the latest master and make changes on top of it? Moreover, somehow it's not running tests on ci at the moment (that's behaviour from the old version).
image
2.

> using a major release of pino in your dependencies can be a reason to bump the major version of nestjs-pino

not sure about that, because there are not any breaking changes, neither in API of the current library nor in [API of `pino` logger](https://github.com/pinojs/pino/releases/tag/v7.0.0): `you should remove @types/pino from your project` – nothing about changed types usage.

3. If you say that it's required for compilation, why do we need it as peer dep instead of dev dep (which is already set)?

**Comment by jarcodallo** [comment]
@iamolegga I opened a new PR #710

**Pull request closed without merging**
