### PR TITLE
feat: use name instead of context

### LINKED ISSUE #97: [FEATURE REQUEST] use "name" instead of "context" for the context
**Is your feature request related to a problem? Please describe.**
I just migrated from another library I used to use `name: {ModuleName}` for the context.
The main reason I did choose this, is that the default key used by [pino-pretty](https://github.com/pinojs/pino-pretty)

I would like to change the context key to use `name` instead.

**Describe the solution you'd like**
I think it would be a good idea to have an extra option at the initialization to define the key used for the context.

**Describe alternatives you've considered**
I tried to implement it, but I didn't weel understood the typing of the options. So I don't know how to add the option.
My code is here : https://github.com/Nhacsam/nestjs-pino/tree/add-param-to-context-key

### PR DESCRIPTION
**Pull request by StevenLangbroek**
closes #97

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
I considered swapping all the method names for `setName` etc., but that would incur a breaking change, and it's kind of an implementation detail.

**Comment by StevenLangbroek** [comment]
Being reworked, hang in there :)

**Comment by StevenLangbroek** [comment]
@iamolegga do you have some time to discuss the expected semantics here? I'm struggling understanding which should take precedence, `PinoLogger`'s `context`, or the `context` coming from `Logger`.

**Comment by StevenLangbroek** [comment]
When `context` is provided from [here](https://github.com/iamolegga/nestjs-pino/blob/master/src/Logger.ts#L10, should it take precedence over `this.context` from the backing `PinoLogger` it calls into (it goes [here](https://github.com/iamolegga/nestjs-pino/blob/master/src/PinoLogger.ts#L89)). The current code seems to suggest `this.context` on `PinoLogger` always blows out `Logger`'s `context`, but if that's the case, then what is the case for it?

**Comment by iamolegga** [comment]
Hello, @StevenLangbroek 

Let's start from [NestJS built-in LoggerService interface](https://github.com/nestjs/nest/blob/master/packages/common/services/logger.service.ts#L11-L17). You can see that it's methods have second or third argument, which name is `context`, and I think this is good default name for argument, which describes the place of execution.

And I also understand, that you may want to change it, this is totally fine, and this could be a good feature. But I preferred to see it as extra property on module params, something like `contextLogsPropertyName` on something similar. This way we could avoid breaking changes

> I'm struggling understanding which should take precedence, PinoLogger's context, or the context coming from Logger.

As `Logger` service is passing execution to `PinoLogger` service, `Logger` has higher order, and context of `PinoLogger` should be replaced with `Logger` context if passed.

> When `context` is provided from [here](https://github.com/iamolegga/nestjs-pino/blob/master/src/Logger.ts#L10), should it take precedence over `this.context` from the backing `PinoLogger` it calls into (it goes [here](https://github.com/iamolegga/nestjs-pino/blob/master/src/PinoLogger.ts#L89)). The current code seems to suggest `this.context` on `PinoLogger` always blows out `Logger`'s `context`, but if that's the case, then what is the case for it?

No, it doesn't. `Object.assign({ context }, firstArg)` here returns object, that will contain context equal to passed context of `Logger`, not `PinoLogger`.

I would recommend to keep the logic as it is now. All you need to do is to provide extra property on module params, and replace the name only on last step, in `PinoLogger`. It's already has injection of params, so it can keep that name, and use it `call` method.

Some clarifying info: this package provides two loggers. One with NestJS built-in Logger interface, the other with pino instance logging interface. So it could be done with code duplication or with composition, which seems to me more practical. So in case `PinoLogger` it works as is, in case of `Logger` it is using as adapter to `PinoLogger`.

I hope I helped you, and you can continue work on this, but if not, I can continue your work, but only when I will find time for this (I hope in next week or two)

**Comment by iamolegga** [comment]
And one more thing, in case of your success I would like to see test that covers this feature, to keep the coverage of package 100%, thank you!

**Comment by iamolegga** [comment]
Hi, @StevenLangbroek I just publish new major version with moving `pino-http` options to separate property, so changing context name should be easy for implementation now. I can do it by myself in a next few days If you don't mind

**Comment by iamolegga** [comment]
closing this pr, as described functionality is implemented in #155

**Pull request closed without merging**
