### PR TITLE
Fix Pino HTTP types

### PR DESCRIPTION
**Pull request by jarcodallo**
This PR will fix the problem with pino and pino-http types.

#699 
pinojs/pino-http#175

### CODE REVIEW

**Comment by jarcodallo** [comment]
Hi @iamolegga please take a look of this PR. I did all the changes as we discussed it in #699

**Comment by iamolegga** [comment]
Hey @jarcodallo , thanks! It looks like it needs to be rebased again (thanks, dependabot) 😅
image
And I'm still wondering do we really need to include `pino` in deps here as it goes as dep of `pino-http`. I'm going to fork your branch and exclude it from the deps to see the result for the test project if it will work without `pino` as a direct dep of this lib

**Comment by jarcodallo** [comment]
> Hey @jarcodallo , thanks! It looks like it needs to be rebased again (thanks, dependabot) 😅 image And I'm still wondering do we really need to include `pino` in deps here as it goes as dep of `pino-http`. I'm going to fork your branch and exclude it from the deps to see the result for the test project if it will work without `pino` as a direct dep of this lib

OMG! remove the deps bot hahaha (flipping the table meme here). 
I included it, because the `@nestjs/platform-fastify` install an old version of pino that need the types from @types/pino package.  I will check if everything work w/o pino in devDeps. Thanks

**Comment by jarcodallo** [comment]
@iamolegga I remove pino from the devDeps and get this error:
image

With pino installed as devDep:
image

**Comment by iamolegga** [comment]
Ok then, let's keep `pino` in deps, I believe we can drop it when `platform-fastify` will be updated.

Thank you very much for this improvement! Merging!

**Comment by jarcodallo** [comment]
> Ok then, let's keep `pino` in deps, I believe we can drop it when `platform-fastify` will be updated.
> 
> Thank you very much for this improvement! Merging!

Happy to help 🚀

**Comment by iamolegga** [comment]
@jarcodallo now I'm thinking which version update should be for this update. major, minor, fix 🤔 API of this lib didn't change, but imports/types of underlying logger have changed slightly

**Comment by jarcodallo** [comment]
> @jarcodallo now I'm thinking which version update should be for this update. major, minor, fix 🤔 API of this lib didn't change, but imports/types of underlying logger have changed slightly

My personal opinion is that you shouldn't update the major version just the minor, because currently v2.x is broken when try to install pino-http@v6 as peer dep.

**Comment by holm** [comment]
Thanks for fixing this. Looking forward to be abe to update `pino` and related libs.

I would also vote for a minor version change for the same reason as @jarcodallo

**Comment by iamolegga** [comment]
Yes, correct, will ship now, thanks, everyone!

**Comment by iamolegga** [comment]
please check out v2.4.0 🎉

**Pull request merged**
